version: '3'
services:
  ipplan:
    image: cent7-ipplan:latest
    container_name: ipplan.sambokit.local
    hostname: ipplan
    domainname: sambokit.local
    network_mode: bridge
    ports:
      - 8081:80
    restart: always
    volumes:
      - /srv/docker-data/ipplan.sambokit.local:/var/www/html
